name: Test App

on:
  push:
    branches:
      - main

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      - name: Analyze code
        run: flutter analyze
    
      - name: Run tests
        run: flutter test

     